# Site settings
title: "Slides"
description: "A place to upload my web-based slides for lectures."
author: "Paul Bryan"
email: pabryan@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
